{{- if .Values.job -}}
{{- $env := include "base.env" . -}}
{{- $proj := include "base.proj" . -}}
{{- $name := include "base.name" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $env }}-{{ $proj }}-{{ $name }}"
  namespace: {{ $env }}-{{ $proj }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: {{ $proj }}-{{ $name }}
        image: {{ .Values.job.imagePath }}:{{ .Values.module_version }}"
        command: ["{{ .Values.job.command }}"]
        {{- if or .Values.job.commandArgs }}
        args:
          {{- range $k, $v := .Values.job.commandArgs }}
          - {{ $v | quote }}
          {{- end }}
        {{- end }}
        {{- if or .Values.job.volumes .Values.job.pvc }}
        volumeMounts:
        {{- if .Values.job.volumes }}
        {{- range .Values.job.volumes }}
        - name: {{ .volumeName | replace "ENV" $env }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
          {{- if .readOnly }}
          readOnly: true
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        env:
        {{- if .Values.job.environments }}
        {{- range $k, $v := .Values.job.environments }}
        {{- range $envname, $envvalue := $v }}
        - name: {{ $envname }}
          value: {{ $envvalue | replace "ENVT" $env | quote}}
        {{- end }}
        {{- end }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.job.resources.requests.cpu }}
            memory: {{ .Values.job.resources.requests.memory }}
          limits:
            cpu: {{ .Values.job.resources.limits.cpu }}
            memory: {{ .Values.job.resources.limits.memory }}
      restartPolicy: Never
      {{- if or .Values.job.volumes .Values.job.pvc}}
      volumes:
        {{- if .Values.job.volumes }}
        {{- range .Values.job.volumes }}
        - name: {{ .volumeName | replace "ENV" $env }}
          {{- if eq .volumeType "emptyDir" }}
          {{ `emptyDir: {}` }}
          {{- else }}
          {{ .volumeType }}:
          {{- end }}
            {{- if eq .volumeType "configMap" }}
            name: {{ .name | replace "APACHE" $name }}
            {{- end }}
            {{- if eq .volumeType "secret" }}
            secretName: {{ .name | replace "APACHE" $name }}
            {{- end }}
            {{- if eq .volumeType "persistentVolumeClaim" }}
            secretName: {{ .name | replace "ENV" $env }}
            {{- end }}
            {{- if .items }}
            items:
            {{- range .items }}
            - key: {{ .key }}
              path: {{ .path }}
            {{- end }}
            {{- end }}
            {{- if eq .volumeType "hostPath" }}
            path: {{ .mountPath }}
            type: {{ .hostPathType }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
