base:

  chartName: "webapp"
  hashicorpv1: true

  deployment:
    replicas: 1
    revisionHistoryLimit: 2
	  imagePath: mayatih/webapp
	
    containerPort:
      - "8080"     

  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: ENV-webapp.stoloto.su
        ca: le # включаем CEM для этого хоста, может быть cem - серт от orglot.office, external - сгенерированный вручную или полученый от внешнего центра сертификации, le - серт от letsencrypt
        paths:
          - path: /

